### ISSUE TITLE
Querying DB for same flags state as an instance

### ISSUE THREAD

**Issue by gamov** [pboling/flag_shih_tzu#46]
I'm currently doing something like this to check the DB for an instance with the same flag state:
```ruby
flags_state = shipping_item.unknown_origin? ? :unknown_origin : :not_unknown_origin
shipment.shipping_items.chained_flags_with('flags', flags_state)
```
It's quite ugly and doesn't scale well if I need to do it for more than one flag. Is there currently a better way to get a complete array of flag states (either *flag* or *not_flag*) for each flag so we can push it to chained_flags_with?

**Comment by pboling** [comment]
That's a really good question.  I do not think there is currently a method providing that ability.

**Comment by pboling** [comment]
If the flag column was named "actions_taken", there is currently a method `all_actions_taken` which returns all the flags on that record as they would be used with `chained_flags_with`

```
user.all_actions_taken
=> [:sent_warm_up_email, :follow_up_called, :sent_final_email, :scheduled_appointment, :referred, :claimed, :not_interested, :sent_web_lead_email]
```

If you used the default flag column name, then the method is:

```
user.all_flags
=> [:sent_warm_up_email, :follow_up_called, :sent_final_email, :scheduled_appointment, :referred, :claimed, :not_interested, :sent_web_lead_email]
```

**Comment by pboling** [comment]
There is also a `selected_flags` (or `selected_<custom_column_name>`) method defined.

```
user.selected_actions_taken
=> [:sent_warm_up_email]
```

It will only return the flags that are marked `true`.

**Comment by gamov** [comment]
@pboling Thanks for your answer!
Yes, I've tried that (I should have mentioned it) but as you say, it doesn't return the negative flags which are needed to query the DB.

**Comment by pboling** [comment]
The first one returns ALL flags, but you are correct, that it does not return them in the state exactly as they would be used to find matching records with `chained_flags_with`.

Still, there is a better way than your example :)

```
# Gives the natural set of all flags
user.all_flags
# => [:sent_warm_up_email, :follow_up_called, :sent_final_email, :scheduled_appointment, :referred]

# Gives only those that are truthy:
selected = user.selected_actions_taken
=> [:sent_warm_up_email]

# Combine!
user.all_flags.inject(selected) {|memo, flag| selected << "not_#{flag}" unless selected.include?(flag) }
=> [:sent_warm_up_email, :not_follow_up_called, :not_sent_final_email, :not_scheduled_appointment, :not_referred]
```

... magic. :8ball:

**Comment by gamov** [comment]
😃

**Comment by pboling** [comment]
Now that I understand the use case it should be pretty easy to add to the gem.  Going to reopen as a reminder to do it.

**Comment by pboling** [comment]
@gamov New methods in 0.3.13:

methods for use with form builders like simple_form:
- chained_flags_with_signature (**this is the one you wanted**)
- chained_#{colmn}_with_signature
- as_flag_collection
- as_#{colmn.singularize}_collection
- selected_flags=
- selected_#{colmn}= (already existed)

**Comment by gamov** [comment]
Awesome work! Thank you very much!
