### ISSUE TITLE
Rails 5 warning - #tables

### ISSUE THREAD

**Issue by bradleybeddoes** [pboling/flag_shih_tzu#54]
Managed to get this gem up and running under a new rails 5 app I am working on without any troubles. Thanks for all the hard work on it!

I am however seeing a warning that is worth reporting:

```
DEPRECATION WARNING: #tables currently returns both tables and views. This behavior is deprecated and will be changed with Rails 5.1 to only return tables. Use #data_sources instead.
```

This occurs within the `has_flags` call (in my specific case with a custom `column` name if that helps).

Do let me know if I can offer any more detail.

**Comment by pboling** [comment]
Interesting.  I will have to look and see what `tables` is being called for.  Thanks for the report!

**Comment by rpbaptist** [comment]
I saw the PR was merged. Thank you for that. Do you have an estimate on when the next release would be?

**Comment by pboling** [comment]
within the next few days.

**Comment by jdelStrother** [comment]
@pboling Anything we can do to help with the release?

**Comment by rpbaptist** [comment]
I found removing FlagShihTzu from the codebase and using true booleans to be a great solution for moving ahead with Rails 5.

**Comment by pboling** [comment]
@jdelStrother I have very little free time at the moment.  I need help fixing the build so I a release.  If anyone would like to volunteer as a maintainer I will happily add them.  I do not have any current projects using flag_shih_tzu myself, as it has a specific use case where it shines.

**Comment by jdelStrother** [comment]
I think #65 should fix the build status, see what you think.

**Comment by pboling** [comment]
This should be fixed in the latest releases!
