### ISSUE TITLE
include?(custom_table_name) missing?

### ISSUE THREAD

**Issue by moonzez** [pboling/flag_shih_tzu#64]
Hey, guys, i think in this row there is a mistake
https://github.com/pboling/flag_shih_tzu/blob/master/lib/flag_shih_tzu.rb#L340
```connection.data_sources```
It should be
```connection.data_sources.include?(custom_table_name)```
otherwise ```has_table``` will be always ```true```

**Comment by pboling** [comment]
Quite right!  I will fix it for release, which should be this weekend.

**Comment by pboling** [comment]
I forgot to fix this for the release, but the good news is the build is finally fixed, so I will fix this shortly and release a new patch of the 0.3 series.

**Comment by pboling** [comment]
Fixed in 0.3.19 release @moonzez

**Comment by moonzez** [comment]
Hey @pboling! Thank you very much!!!
